// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: gzk14oXgaAXzvGY4rg9Zpf
// Component: aIK15ggyc1p
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import AsFeaturedIn from "../../AsFeaturedIn"; // plasmic-import: AG2XBIi7yI/component
import ReviewCard from "../../ReviewCard"; // plasmic-import: SHXv-rndbh/component
import SideCta from "../../SideCta"; // plasmic-import: sdBBiB4Cb3/component

import { useScreenVariants as useScreenVariantsbai21PvFaWEr } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: BAI21pvFA_wEr/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_sparq.module.css"; // plasmic-import: gzk14oXgaAXzvGY4rg9Zpf/projectcss
import sty from "./PlasmicArticleBody.module.css"; // plasmic-import: aIK15ggyc1p/css

export type PlasmicArticleBody__VariantMembers = {};
export type PlasmicArticleBody__VariantsArgs = {};
type VariantPropType = keyof PlasmicArticleBody__VariantsArgs;
export const PlasmicArticleBody__VariantProps = new Array<VariantPropType>();

export type PlasmicArticleBody__ArgsType = {};
type ArgPropType = keyof PlasmicArticleBody__ArgsType;
export const PlasmicArticleBody__ArgProps = new Array<ArgPropType>();

export type PlasmicArticleBody__OverridesType = {
  body?: p.Flex<"div">;
  article?: p.Flex<"div">;
  articleBody?: p.Flex<"div">;
  asFeaturedIn?: p.Flex<typeof AsFeaturedIn>;
  link?: p.Flex<"a"> & Partial<LinkProps>;
  button?: p.Flex<"button">;
  reviews?: p.Flex<"div">;
  freeBox?: p.Flex<"div">;
  sideCta?: p.Flex<typeof SideCta>;
};

export interface DefaultArticleBodyProps {
  className?: string;
}

const __wrapUserFunction =
  globalThis.__PlasmicWrapUserFunction ?? ((loc, fn) => fn());
const __wrapUserPromise =
  globalThis.__PlasmicWrapUserPromise ??
  (async (loc, promise) => {
    return await promise;
  });

function PlasmicArticleBody__RenderFunc(props: {
  variants: PlasmicArticleBody__VariantsArgs;
  args: PlasmicArticleBody__ArgsType;
  overrides: PlasmicArticleBody__OverridesType;

  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = p.useCurrentUser?.() || {};
  const [$queries, setDollarQueries] = React.useState({});

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsbai21PvFaWEr()
  });

  return (
    <div
      data-plasmic-name={"body"}
      data-plasmic-override={overrides.body}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        sty.body
      )}
    >
      <div className={classNames(projectcss.all, sty.columns__nOsV0)}>
        <div
          data-plasmic-name={"article"}
          data-plasmic-override={overrides.article}
          className={classNames(projectcss.all, sty.article)}
        >
          {true ? (
            <div
              data-plasmic-name={"articleBody"}
              data-plasmic-override={overrides.articleBody}
              className={classNames(projectcss.all, sty.articleBody)}
            >
              <AsFeaturedIn
                data-plasmic-name={"asFeaturedIn"}
                data-plasmic-override={overrides.asFeaturedIn}
                className={classNames("__wab_instance", sty.asFeaturedIn)}
              />

              <p.PlasmicImg
                alt={""}
                className={classNames(sty.img__mhNf)}
                displayHeight={"auto" as const}
                displayMaxHeight={"none" as const}
                displayMaxWidth={"100%" as const}
                displayMinHeight={"0" as const}
                displayMinWidth={"0" as const}
                displayWidth={"100%" as const}
                link={
                  "https://www.quittinghacks.com/rechargeable-offer/" as const
                }
                loading={"lazy" as const}
                src={{
                  src: "/plasmic/sparq/images/_9B498Fb8RechargableGif11Gif.gif",
                  fullWidth: 614,
                  fullHeight: 332,
                  aspectRatio: undefined
                }}
              />

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__zbhgt
                )}
              >
                <React.Fragment>
                  <React.Fragment>
                    {
                      "Imagine being nic-free but still getting that oh-so-satisfying throat hit along with delicious natural flavoring?\n\nIt almost sounds too good to be true, right? \n\nThe solution is simple... \n\nChoose natural ingredients, "
                    }
                  </React.Fragment>
                  <span
                    className={"plasmic_default__all plasmic_default__span"}
                    style={{ fontWeight: 700 }}
                  >
                    {"NOT"}
                  </span>
                  <React.Fragment>
                    {" Stimulants and Harmful Chemicals:"}
                  </React.Fragment>
                </React.Fragment>
              </div>

              <p.PlasmicLink
                data-plasmic-name={"link"}
                data-plasmic-override={overrides.link}
                className={classNames(projectcss.all, projectcss.a, sty.link)}
                component={Link}
                href={
                  "https://www.quittinghacks.com/rechargeable-offer/" as const
                }
                platform={"nextjs"}
              >
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__zJyj8)}
                  displayHeight={"auto" as const}
                  displayMaxHeight={"none" as const}
                  displayMaxWidth={"100%" as const}
                  displayMinHeight={"0" as const}
                  displayMinWidth={"0" as const}
                  displayWidth={"100%" as const}
                  loading={"lazy" as const}
                  src={{
                    src: "/plasmic/sparq/images/screenshot20230224At43442PMpng.png",
                    fullWidth: 2352,
                    fullHeight: 802,
                    aspectRatio: undefined
                  }}
                />
              </p.PlasmicLink>

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__zbyyq
                )}
              >
                <React.Fragment>
                  <React.Fragment>
                    {
                      "Sparq Zero® is the evolution of inhalation. \n\nOur revolutionary diffuser comes in your choice of natural Sweet Mango or natural Cool Mint, providing you with the throat hit and intense flavoring you’re looking for... "
                    }
                  </React.Fragment>
                  <span
                    className={"plasmic_default__all plasmic_default__span"}
                    style={{ fontWeight: 700 }}
                  >
                    {"without the guilt! "}
                  </span>
                  <React.Fragment>
                    {
                      "\n\nWe spent 6 years developing a device that was health-focused, lab-tested and that produced real throat hit and flavor that would effectively eliminate your cravings."
                    }
                  </React.Fragment>
                </React.Fragment>
              </div>

              <p.PlasmicImg
                alt={""}
                className={classNames(sty.img__aJloq)}
                displayHeight={"auto" as const}
                displayMaxHeight={"none" as const}
                displayMaxWidth={"100%" as const}
                displayMinHeight={"0" as const}
                displayMinWidth={"0" as const}
                displayWidth={"100%" as const}
                link={
                  "https://www.quittinghacks.com/rechargeable-offer/" as const
                }
                loading={"lazy" as const}
                src={{
                  src: "/plasmic/sparq/images/fbfd287ERechargableGif21Gif.gif",
                  fullWidth: 614,
                  fullHeight: 332,
                  aspectRatio: undefined
                }}
              />

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___3BCi
                )}
              >
                {
                  "Absolutely no expense was spared with regard to design-form and function:\n\nThis ultra-modern metal device is slim, compact, odorless, and easy to use at any time or place."
                }
              </div>

              <p.PlasmicImg
                alt={""}
                className={classNames(sty.img__j8Rs)}
                displayHeight={"auto" as const}
                displayMaxHeight={"none" as const}
                displayMaxWidth={"100%" as const}
                displayMinHeight={"0" as const}
                displayMinWidth={"0" as const}
                displayWidth={"100%" as const}
                loading={"lazy" as const}
                src={{
                  src: "/plasmic/sparq/images/_4B6E6Ed1Devicegif.gif",
                  fullWidth: 669,
                  fullHeight: 575,
                  aspectRatio: undefined
                }}
              />

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___0CEqr
                )}
              >
                <React.Fragment>
                  <React.Fragment>
                    {
                      "Plus it comes it comes in your choice of two delicious flavors, Sweet Mango or Cool Mint!\n\nWe even offer a "
                    }
                  </React.Fragment>
                  <span
                    className={"plasmic_default__all plasmic_default__span"}
                    style={{ fontWeight: 700 }}
                  >
                    {"money-back guarantee"}
                  </span>
                  <React.Fragment>
                    {" if you don't absolutely love the taste and throat hit. "}
                  </React.Fragment>
                </React.Fragment>
              </div>

              <p.PlasmicImg
                alt={""}
                className={classNames(sty.img__r4Vo8)}
                displayHeight={"auto" as const}
                displayMaxHeight={"none" as const}
                displayMaxWidth={"100%" as const}
                displayMinHeight={"0" as const}
                displayMinWidth={"0" as const}
                displayWidth={"100%" as const}
                loading={"lazy" as const}
                src={{
                  src: "/plasmic/sparq/images/_6Bb5E2F0Image31000000000000000000028Png.png",
                  fullWidth: 614,
                  fullHeight: 332,
                  aspectRatio: undefined
                }}
              />

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__qIfFz
                )}
              >
                <React.Fragment>
                  <React.Fragment>
                    {
                      "Most importantly, ALL of our formulations have undergone extensive lab-testing.\n\nThe test results verified our all-natural, plant-based pod ingredients are safe even when heated into a vapor.\n\n"
                    }
                  </React.Fragment>
                  {
                    <ul
                      className={classNames(
                        projectcss.all,
                        projectcss.ul,
                        sty.ul__tGHl
                      )}
                    >
                      <li
                        className={classNames(
                          projectcss.all,
                          projectcss.li,
                          projectcss.__wab_text,
                          sty.li__xZakq
                        )}
                      >
                        {
                          "no harmful byproducts produced during the heating process (Gas chromatography)"
                        }
                      </li>
                    </ul>
                  }
                  <React.Fragment>{"\n"}</React.Fragment>
                  {
                    <ul
                      className={classNames(
                        projectcss.all,
                        projectcss.ul,
                        sty.ul__g6MwK
                      )}
                    >
                      <li
                        className={classNames(
                          projectcss.all,
                          projectcss.li,
                          projectcss.__wab_text,
                          sty.li__pxdHw
                        )}
                      >
                        {"no evidence of carbonyl compounds"}
                      </li>
                    </ul>
                  }
                  <React.Fragment>{"\n"}</React.Fragment>
                  {
                    <ul
                      className={classNames(
                        projectcss.all,
                        projectcss.ul,
                        sty.ul__tJas
                      )}
                    >
                      <li
                        className={classNames(
                          projectcss.all,
                          projectcss.li,
                          projectcss.__wab_text,
                          sty.li___5Ddp
                        )}
                      >
                        {
                          "no evidence of “bad characters” known in the industry, including Diacetyl, Acrolein and Acetoin"
                        }
                      </li>
                    </ul>
                  }
                  <React.Fragment>{""}</React.Fragment>
                </React.Fragment>
              </div>

              <p.PlasmicImg
                alt={""}
                className={classNames(sty.img__xgNz9)}
                displayHeight={"auto" as const}
                displayMaxHeight={"none" as const}
                displayMaxWidth={"100%" as const}
                displayMinHeight={"0" as const}
                displayMinWidth={"0" as const}
                displayWidth={"100%" as const}
                loading={"lazy" as const}
                src={{
                  src: "/plasmic/sparq/images/_12A7A7BbTestingSmallerImage10Yy0Fa0000000000000281Png.png",
                  fullWidth: 1258,
                  fullHeight: 550,
                  aspectRatio: undefined
                }}
              />

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___1X2Du
                )}
              >
                <React.Fragment>
                  <span
                    className={"plasmic_default__all plasmic_default__span"}
                    style={{ fontWeight: 700 }}
                  >
                    {"Figure 1:"}
                  </span>
                  <React.Fragment>
                    {
                      " ISO-Accredited Laboratory certified safety and ensured the liquid remains stable even when heated."
                    }
                  </React.Fragment>
                </React.Fragment>
              </div>

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__jt4Ir
                )}
              >
                <React.Fragment>
                  <React.Fragment>
                    {
                      "We are incredibly proud to state that we have helped over 100,000 people quit while still allowing them to enjoy their habit, without any guilt!\n\nWe’ve made it easy for you to do the same, by offering a "
                    }
                  </React.Fragment>
                  <span
                    className={"plasmic_default__all plasmic_default__span"}
                    style={{ fontWeight: 700 }}
                  >
                    {"FREE"}
                  </span>
                  <React.Fragment>
                    {
                      " box of our Sweet Mango or Cool Mint pods, with your first purchase, auto-applied at checkout."
                    }
                  </React.Fragment>
                </React.Fragment>
              </div>

              <p.PlasmicImg
                alt={""}
                className={classNames(sty.img__dpMz6)}
                displayHeight={"auto" as const}
                displayMaxHeight={"none" as const}
                displayMaxWidth={"100%" as const}
                displayMinHeight={"0" as const}
                displayMinWidth={"0" as const}
                displayWidth={"100%" as const}
                loading={"lazy" as const}
                src={{
                  src: "/plasmic/sparq/images/_7048E521Hit110000000000000000000281Png.png",
                  fullWidth: 614,
                  fullHeight: 332,
                  aspectRatio: undefined
                }}
              />

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__axNCu
                )}
              >
                <React.Fragment>
                  <span
                    className={"plasmic_default__all plasmic_default__span"}
                    style={{ fontWeight: 700 }}
                  >
                    {"Click Here to Claim Free Sweet Mango or Cool Mint Pods!"}
                  </span>
                </React.Fragment>
              </div>

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__jks7P
                )}
              >
                {"Fast Same Day Shipping"}
              </div>

              <div className={classNames(projectcss.all, sty.columns__i8Cp)}>
                <div className={classNames(projectcss.all, sty.column__aepe3)}>
                  <button
                    data-plasmic-name={"button"}
                    data-plasmic-override={overrides.button}
                    className={classNames(
                      projectcss.all,
                      projectcss.button,
                      projectcss.__wab_text,
                      sty.button
                    )}
                  >
                    {"CLAIM FREE PODS 👉"}
                  </button>
                </div>

                <div className={classNames(projectcss.all, sty.column__cc2J3)}>
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img___4Ldwn)}
                    displayHeight={"auto" as const}
                    displayMaxHeight={"none" as const}
                    displayMaxWidth={"100%" as const}
                    displayMinHeight={"0" as const}
                    displayMinWidth={"0" as const}
                    displayWidth={"auto" as const}
                    loading={"lazy" as const}
                    src={{
                      src: "/plasmic/sparq/images/dividersvg.bin",
                      fullWidth: 5,
                      fullHeight: 150,
                      aspectRatio: 0.033333
                    }}
                  />
                </div>

                <div className={classNames(projectcss.all, sty.column___2Smb)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___5Of3I
                    )}
                  >
                    {hasVariant(globalVariants, "screen", "desktopOnly")
                      ? "100,000+ Happy Customers! In Stock - Ships Now."
                      : "100,000+ Happy Customers! In Stock - Ships Now."}
                  </div>

                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__mki6C)}
                    displayHeight={"auto" as const}
                    displayMaxHeight={"none" as const}
                    displayMaxWidth={"100%" as const}
                    displayMinHeight={"0" as const}
                    displayMinWidth={"0" as const}
                    displayWidth={"auto" as const}
                    loading={"lazy" as const}
                    src={{
                      src: "/plasmic/sparq/images/starpng2.png",
                      fullWidth: 142,
                      fullHeight: 21,
                      aspectRatio: undefined
                    }}
                  />
                </div>
              </div>

              <p.PlasmicImg
                alt={""}
                className={classNames(sty.img__beBwu)}
                displayHeight={"auto" as const}
                displayMaxHeight={"none" as const}
                displayMaxWidth={"100%" as const}
                displayMinHeight={"0" as const}
                displayMinWidth={"0" as const}
                displayWidth={"100%" as const}
                loading={"lazy" as const}
                src={{
                  src: "/plasmic/sparq/images/silverDeviceOutrogif.gif",
                  fullWidth: 669,
                  fullHeight: 575,
                  aspectRatio: undefined
                }}
              />
            </div>
          ) : null}
        </div>

        {true ? (
          <div
            data-plasmic-name={"reviews"}
            data-plasmic-override={overrides.reviews}
            className={classNames(projectcss.all, sty.reviews)}
          >
            <div
              data-plasmic-name={"freeBox"}
              data-plasmic-override={overrides.freeBox}
              className={classNames(projectcss.all, sty.freeBox)}
            >
              <ReviewCard
                className={classNames("__wab_instance", sty.reviewCard__gk4En)}
              />

              <ReviewCard
                className={classNames("__wab_instance", sty.reviewCard__giGlD)}
              />

              <ReviewCard
                className={classNames("__wab_instance", sty.reviewCard__dIell)}
              />

              <SideCta
                data-plasmic-name={"sideCta"}
                data-plasmic-override={overrides.sideCta}
                className={classNames("__wab_instance", sty.sideCta)}
              />
            </div>
          </div>
        ) : null}
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  body: [
    "body",
    "article",
    "articleBody",
    "asFeaturedIn",
    "link",
    "button",
    "reviews",
    "freeBox",
    "sideCta"
  ],
  article: ["article", "articleBody", "asFeaturedIn", "link", "button"],
  articleBody: ["articleBody", "asFeaturedIn", "link", "button"],
  asFeaturedIn: ["asFeaturedIn"],
  link: ["link"],
  button: ["button"],
  reviews: ["reviews", "freeBox", "sideCta"],
  freeBox: ["freeBox", "sideCta"],
  sideCta: ["sideCta"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  body: "div";
  article: "div";
  articleBody: "div";
  asFeaturedIn: typeof AsFeaturedIn;
  link: "a";
  button: "button";
  reviews: "div";
  freeBox: "div";
  sideCta: typeof SideCta;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicArticleBody__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicArticleBody__VariantsArgs;
    args?: PlasmicArticleBody__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicArticleBody__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicArticleBody__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicArticleBody__ArgProps,
          internalVariantPropNames: PlasmicArticleBody__VariantProps
        }),
      [props, nodeName]
    );

    return PlasmicArticleBody__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "body") {
    func.displayName = "PlasmicArticleBody";
  } else {
    func.displayName = `PlasmicArticleBody.${nodeName}`;
  }
  return func;
}

export const PlasmicArticleBody = Object.assign(
  // Top-level PlasmicArticleBody renders the root element
  makeNodeComponent("body"),
  {
    // Helper components rendering sub-elements
    article: makeNodeComponent("article"),
    articleBody: makeNodeComponent("articleBody"),
    asFeaturedIn: makeNodeComponent("asFeaturedIn"),
    link: makeNodeComponent("link"),
    button: makeNodeComponent("button"),
    reviews: makeNodeComponent("reviews"),
    freeBox: makeNodeComponent("freeBox"),
    sideCta: makeNodeComponent("sideCta"),

    // Metadata about props expected for PlasmicArticleBody
    internalVariantProps: PlasmicArticleBody__VariantProps,
    internalArgProps: PlasmicArticleBody__ArgProps
  }
);

export default PlasmicArticleBody;
/* prettier-ignore-end */
