// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: gzk14oXgaAXzvGY4rg9Zpf
// Component: LQC4_SZ5LlT
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import ArticleNav from "../../ArticleNav"; // plasmic-import: 19Otlemsjn/component
import ArticleIntro from "../../ArticleIntro"; // plasmic-import: 4w-gEvjCCP/component
import ArticleBody from "../../ArticleBody"; // plasmic-import: aIK15ggyc1p/component

import { useScreenVariants as useScreenVariantsbai21PvFaWEr } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: BAI21pvFA_wEr/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_sparq.module.css"; // plasmic-import: gzk14oXgaAXzvGY4rg9Zpf/projectcss
import sty from "./PlasmicBlog2.module.css"; // plasmic-import: LQC4_SZ5LlT/css

export type PlasmicBlog2__VariantMembers = {};
export type PlasmicBlog2__VariantsArgs = {};
type VariantPropType = keyof PlasmicBlog2__VariantsArgs;
export const PlasmicBlog2__VariantProps = new Array<VariantPropType>();

export type PlasmicBlog2__ArgsType = {};
type ArgPropType = keyof PlasmicBlog2__ArgsType;
export const PlasmicBlog2__ArgProps = new Array<ArgPropType>();

export type PlasmicBlog2__OverridesType = {
  root?: p.Flex<"div">;
  articleNav?: p.Flex<typeof ArticleNav>;
  articleIntro?: p.Flex<typeof ArticleIntro>;
  articleBody?: p.Flex<typeof ArticleBody>;
};

export interface DefaultBlog2Props {}

const __wrapUserFunction =
  globalThis.__PlasmicWrapUserFunction ?? ((loc, fn) => fn());
const __wrapUserPromise =
  globalThis.__PlasmicWrapUserPromise ??
  (async (loc, promise) => {
    return await promise;
  });

function PlasmicBlog2__RenderFunc(props: {
  variants: PlasmicBlog2__VariantsArgs;
  args: PlasmicBlog2__ArgsType;
  overrides: PlasmicBlog2__OverridesType;

  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;
  const __nextRouter = useRouter();

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = p.useCurrentUser?.() || {};
  const [$queries, setDollarQueries] = React.useState({});

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsbai21PvFaWEr()
  });

  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            sty.root
          )}
        >
          {(
            hasVariant(globalVariants, "screen", "largestMobile")
              ? true
              : hasVariant(globalVariants, "screen", "smallestMobile")
              ? true
              : true
          ) ? (
            <ArticleNav
              data-plasmic-name={"articleNav"}
              data-plasmic-override={overrides.articleNav}
              className={classNames("__wab_instance", sty.articleNav)}
            />
          ) : null}

          <ArticleIntro
            data-plasmic-name={"articleIntro"}
            data-plasmic-override={overrides.articleIntro}
            className={classNames("__wab_instance", sty.articleIntro)}
          />

          <ArticleBody
            data-plasmic-name={"articleBody"}
            data-plasmic-override={overrides.articleBody}
            className={classNames("__wab_instance", sty.articleBody)}
          />
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "articleNav", "articleIntro", "articleBody"],
  articleNav: ["articleNav"],
  articleIntro: ["articleIntro"],
  articleBody: ["articleBody"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  articleNav: typeof ArticleNav;
  articleIntro: typeof ArticleIntro;
  articleBody: typeof ArticleBody;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicBlog2__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicBlog2__VariantsArgs;
    args?: PlasmicBlog2__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicBlog2__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicBlog2__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicBlog2__ArgProps,
          internalVariantPropNames: PlasmicBlog2__VariantProps
        }),
      [props, nodeName]
    );

    return PlasmicBlog2__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicBlog2";
  } else {
    func.displayName = `PlasmicBlog2.${nodeName}`;
  }
  return func;
}

export const PlasmicBlog2 = Object.assign(
  // Top-level PlasmicBlog2 renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    articleNav: makeNodeComponent("articleNav"),
    articleIntro: makeNodeComponent("articleIntro"),
    articleBody: makeNodeComponent("articleBody"),

    // Metadata about props expected for PlasmicBlog2
    internalVariantProps: PlasmicBlog2__VariantProps,
    internalArgProps: PlasmicBlog2__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicBlog2;
/* prettier-ignore-end */
