// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: gzk14oXgaAXzvGY4rg9Zpf
// Component: ydhgdf7rb8

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/react-web/lib/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import Blog4 from "../../Blog4"; // plasmic-import: 0dDWejRqGs/component

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_sparq_master_app.module.css"; // plasmic-import: gzk14oXgaAXzvGY4rg9Zpf/projectcss
import sty from "./PlasmicBlogTest.module.css"; // plasmic-import: ydhgdf7rb8/css

export type PlasmicBlogTest__VariantMembers = {};
export type PlasmicBlogTest__VariantsArgs = {};
type VariantPropType = keyof PlasmicBlogTest__VariantsArgs;
export const PlasmicBlogTest__VariantProps = new Array<VariantPropType>();

export type PlasmicBlogTest__ArgsType = {};
type ArgPropType = keyof PlasmicBlogTest__ArgsType;
export const PlasmicBlogTest__ArgProps = new Array<ArgPropType>();

export type PlasmicBlogTest__OverridesType = {
  root?: p.Flex<"div">;
  blog4?: p.Flex<typeof Blog4>;
};

export interface DefaultBlogTestProps {}

const __wrapUserFunction =
  globalThis.__PlasmicWrapUserFunction ?? ((loc, fn) => fn());
const __wrapUserPromise =
  globalThis.__PlasmicWrapUserPromise ??
  (async (loc, promise) => {
    return await promise;
  });

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicBlogTest__RenderFunc(props: {
  variants: PlasmicBlogTest__VariantsArgs;
  args: PlasmicBlogTest__ArgsType;
  overrides: PlasmicBlogTest__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;
  const __nextRouter = useNextRouter();

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = p.useCurrentUser?.() || {};
  const [$queries, setDollarQueries] = React.useState({});

  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            sty.root
          )}
        >
          <Blog4
            data-plasmic-name={"blog4"}
            data-plasmic-override={overrides.blog4}
            className={classNames("__wab_instance", sty.blog4)}
          />
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "blog4"],
  blog4: ["blog4"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  blog4: typeof Blog4;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicBlogTest__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicBlogTest__VariantsArgs;
    args?: PlasmicBlogTest__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicBlogTest__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicBlogTest__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicBlogTest__ArgProps,
          internalVariantPropNames: PlasmicBlogTest__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicBlogTest__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicBlogTest";
  } else {
    func.displayName = `PlasmicBlogTest.${nodeName}`;
  }
  return func;
}

export const PlasmicBlogTest = Object.assign(
  // Top-level PlasmicBlogTest renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    blog4: makeNodeComponent("blog4"),

    // Metadata about props expected for PlasmicBlogTest
    internalVariantProps: PlasmicBlogTest__VariantProps,
    internalArgProps: PlasmicBlogTest__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicBlogTest;
/* prettier-ignore-end */
